import './globals.css';
import type { Metadata } from 'next';
import { Mona_Sans } from 'next/font/google';

const MonaSans = Mona_Sans({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${MonaSans.className} text-neutral-800 antialiased`}>
                {children}
            </body>
        </html>
    );
}
